### ISSUE TITLE
unsupported text language

### ISSUE THREAD

**Issue by AlburraqDeveloper** [ibm-cloud-docs/natural-language-understanding#67]
doc says that Watson API supports different languages list is given URL:

https://cloud.ibm.com/docs/natural-language-understanding?topic=natural-language-understanding-detectable-languages

but when I used Spanish or German it gives me an error unsupported language: 'es'

**Comment by SirSpidey** [comment]
It might be because there is not enough source text
> it is recommended that you use text with at least 100 characters. 

You can also override the detection by [specifying the language](https://cloud.ibm.com/docs/natural-language-understanding?topic=natural-language-understanding-overriding-language-detection)

If you still have issues with your code, you can post to [Stack Overflow](https://stackoverflow.com/questions/tagged/watson-nlu) or [IBM Cloud Support](https://cloud.ibm.com/unifiedsupport/supportcenter)
